# Generated by Django 4.2.23 on 2025-08-02 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotion',
            name='date',
        ),
        migrations.AddField(
            model_name='devotion',
            name='ddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
