# Generated by Django 4.2.23 on 2025-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0002_remove_devotion_date_devotion_ddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotion',
            old_name='ddate',
            new_name='date',
        ),
    ]
