# Generated by Django 4.2.23 on 2025-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0003_rename_ddate_devotion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
