# Generated by Django 4.2.23 on 2025-08-04 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devotions', '0004_devotion_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devotion',
            name='scripture',
            field=models.CharField(max_length=255),
        ),
    ]
